name: CI

on: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build arai2c.exe
      run: |
        sudo docker build -t aria2-mingw - < Dockerfile.mingw
        id=$(sudo docker create aria2-mingw)
        sudo docker cp $id:/aria2/src/aria2c.exe .
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: aria2c.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
